name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 14.15.1 # We're targeting this release of Node because we aren't on >=14.18 yet.
          - 16
          - 18

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # Node 14 still ships with npm@6 so for compatibility reasons we're upping
      # this to match everything else.
      - name: Install npm@8
        if: matrix.node-version == '14.15.1'
        run: npm install -g npm@8

      - run: npm ci
      - run: npm test
