name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4

      - uses: actions/setup-node@v2.3.0
        with:
          node-version: 14.15.1

      - run: npm install -g npm@7
      - run: npm ci
      - run: npm test
